fix reporting PHP errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,12 +43,15 @@ jobs:
     - name: Check PHP errors
       shell: bash
       run: |
-        set +e
-        set +o pipefail
         CONTAINER=`docker container ls -l -q`
-        docker container logs $CONTAINER 2>&1 | grep -q 'php7' && \
-          ( echo 'No PHP errors found' && exit 0 ) || \
-          ( echo 'PHP reported errors or warnings; see log below' && exit 1 )
+        if docker container logs $CONTAINER 2>&1 | grep -q 'php7'; then
+          echo 'PHP reported errors or warnings:'
+          docker container logs $CONTAINER 2>&1 | grep 'php7'
+          exit 1
+        else
+          echo 'No PHP errors found'
+          exit 0
+        fi
     #
     # If any of the tests fail, let's grab a bit more detail on the environment
     #
